<a href="https://colab.research.google.com/github/ShawnSchmucker/MAE-494-Fall-2022/blob/main/MAE_494_HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1**

In [10]:
import numpy as np
from scipy.optimize import minimize

f = lambda x: (x[0] - x[1])**2 + (x[1] + x[2] - 2)**2 + (x[3] - 1)**2 + (x[4] - 1)**2

x0 = [1, 1, 1, 1, 1]

cons = ({'type': 'eq', 'fun': lambda x: x[0] + 3*x[1]},
        {'type': 'eq', 'fun': lambda x: x[2] + x[3] - 2*x[4]},
        {'type': 'eq', 'fun': lambda x: x[1] - x[4]})

bnds = ((-10,10),(-10,10),(-10,10),(-10,10),(-10,10))

res = minimize(f, x0, method='SLSQP', bounds=bnds, constraints=cons)

print(res.x)

x01 = [0, 0, 0, 0, 0]

res1 = minimize(f, x01, method='SLSQP', bounds=bnds, constraints=cons)

print(res1.x)

x02 = [5, 5, 5, 5, 5]

res2 = minimize(f, x02, method='SLSQP', bounds=bnds, constraints=cons)

print(res2.x)

[-0.76749312  0.25583104  0.62795044 -0.11628835  0.25583104]
[-0.76744186  0.25581395  0.62790698 -0.11627907  0.25581395]
[-0.76740731  0.25580244  0.62794182 -0.11633695  0.25580244]


The inital guess was 1 for every variable. Changing the initial guess (to 0, then to 5) resulted in slightly different solutions each time, though the same to three or four digits.

**Problem 2**

*(a)* $g(x) = \nabla f(x) = b + (A + A^T) x$

$\quad H(x) = \nabla g(x) = A + A^T$

*(b)* $\text{First order: } f(x) \approx f(0) + g(0)^T (x - 0)$

$\qquad = 0 + (b + 0)^T x$

$\qquad = b^T x$

$\quad \text{Second order: } f(x) \approx f(0) + g(0)^T (x - 0) + {1 \over 2} (x - 0)^T H(0) (x - 0)$

$\qquad = 0 + (b + 0)^T x + {1 \over 2} x^T (A + A^T) x$

$\qquad = b^T x + {1 \over 2} x^T (A + A^T) x$

$\quad \text{The second order approximation is exact. The first order approximation is not.}$

*(c)* $\text{If all eigenvalues of } A \text{ are greater than 0, then } A \text{ is positive definite.}$

*(d)* $\text{If the determinant of } A \text{ is not equal to 0, then } A \text{ has full rank.}$

*(e)* $\text{In order for } Ax = b \text{ to have a solution for } x \text{, } b \text{ must be orthogonal to } y.$

**Problem 3**

$\text{minimize } P(x) = x^Tc$

$\text{s.t. } D_j(x) = x^Ta_j \geq b_j \text{ for } j = 1,2,...M$

$\text{where } x \in \mathbb{N}^N \text{, } x_i > 0 \text{ for } i = 1,2,...N \text{ is the amount of each food type purchased, }$

$\text{and } D_j \text{ is the function corresponding to } a_j \in \mathbb{R}^N \text{, which is the } j \text{th column in } A,$

$\text{where } A = \begin{bmatrix}
a_{1,1} & a_{1,2} & \cdots & a_{1,M} \\
a_{2,1} & a_{2,2} & \cdots & a_{2,M} \\
\vdots & \vdots & \ddots & \vdots \\
a_{N,1} & a_{N,2} & \cdots & a_{N,M}
\end{bmatrix}$